export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1600px",
    margin: "0 auto",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 24px",
    borderRadius: "12px",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  brandText: {
    fontSize: "18px",
    fontWeight: "800",
    letterSpacing: "1px",
  },
  userProfile: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  userInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-end",
    gap: "2px",
  },
  userName: {
    fontSize: "14px",
    fontWeight: "700",
  },
  banner: {
    borderWidth: "1px",
    borderStyle: "solid",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "14px",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "280px 1fr",
    gap: "20px",
    flex: 1,
  },
  sidebar: {
    padding: "16px",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    height: "fit-content",
  },
  tabBtn: {
    width: "100%",
    padding: "12px 16px",
    textAlign: "left",
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    fontSize: "14px",
    fontWeight: "600",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  activeTabBtn: {
    width: "100%",
    padding: "12px 16px",
    textAlign: "left",
    background: "var(--primary-glow)",
    border: "none",
    color: "var(--primary)",
    fontSize: "14px",
    fontWeight: "700",
    borderRadius: "8px",
    cursor: "pointer",
    boxShadow: "inset 0 0 10px rgba(249,115,22,0.1)",
  },
  workspace: {
    padding: "32px",
    borderRadius: "16px",
    minHeight: "650px",
  },
  tabContent: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  splitLayout: {
    display: "flex",
    gap: "24px",
    flexWrap: "wrap",
  },
  formPanel: {
    padding: "24px",
    borderRadius: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    flex: 1,
    background: "rgba(255,255,255,0.01)",
    border: "1px solid rgba(255,255,255,0.04)",
  },
  tableWrapper: {
    overflowX: "auto",
    background: "rgba(255,255,255,0.01)",
    border: "1px solid var(--card-border)",
    borderRadius: "12px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
    fontSize: "14px",
  },
  loading: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    color: "var(--primary)",
    fontWeight: "700",
    fontSize: "18px",
  },
  row: {
    display: "flex",
    gap: "16px",
  }
};
