export const styles = {
  container: {
    padding: "24px",
    maxWidth: "1600px",
    margin: "0 auto",
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px 24px",
    borderRadius: "12px",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  brandText: {
    fontSize: "18px",
    fontWeight: "800",
    letterSpacing: "1px",
  },
  userProfile: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flexWrap: "wrap",
  },
  profileTrigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: "12px",
    padding: "6px 10px 6px 6px",
    background: "rgba(15, 23, 42, 0.45)",
    border: "1px solid rgba(148, 163, 184, 0.18)",
    borderRadius: "999px",
    cursor: "pointer",
    color: "inherit",
    transition: "transform 0.2s ease, border-color 0.2s ease, box-shadow 0.2s ease",
  },
  profileTriggerHover: {
    transform: "translateY(-1px) scale(1.01)",
    borderColor: "rgba(96, 165, 250, 0.42)",
    boxShadow: "0 10px 26px rgba(15, 23, 42, 0.26)",
  },
  avatarFrame: {
    width: "40px",
    height: "40px",
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
    borderRadius: "50%",
    border: "1px solid rgba(255, 255, 255, 0.18)",
    background: "linear-gradient(135deg, rgba(59, 130, 246, 0.4), rgba(99, 102, 241, 0.2))",
    flexShrink: 0,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover",
  },
  avatarFallback: {
    color: "#f8fafc",
    fontSize: "14px",
    fontWeight: "800",
    letterSpacing: "0.06em",
    textTransform: "uppercase",
  },
  userInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: "2px",
    textAlign: "left",
  },
  userName: {
    fontSize: "14px",
    fontWeight: "700",
  },
  rewardPill: {
    background: "linear-gradient(135deg, #f59e0b, #d97706)",
    borderRadius: "20px",
    padding: "6px 14px",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    boxShadow: "0 2px 10px rgba(245,158,11,0.35)",
    animation: "fadeIn 0.5s ease",
  },
  rewardPillText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: "13px",
    whiteSpace: "nowrap",
  },
  banner: {
    borderWidth: "1px",
    borderStyle: "solid",
    padding: "12px 24px",
    borderRadius: "8px",
    fontSize: "14px",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "280px 1fr",
    gap: "20px",
    flex: 1,
  },
  sidebar: {
    padding: "16px",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    height: "fit-content",
  },
  tabBtn: {
    width: "100%",
    padding: "12px 16px",
    textAlign: "left",
    background: "transparent",
    border: "none",
    color: "#94a3b8",
    fontSize: "14px",
    fontWeight: "600",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.2s ease",
  },
  activeTabBtn: {
    width: "100%",
    padding: "12px 16px",
    textAlign: "left",
    background: "var(--primary-glow)",
    border: "none",
    color: "var(--primary)",
    fontSize: "14px",
    fontWeight: "700",
    borderRadius: "8px",
    cursor: "pointer",
    boxShadow: "inset 0 0 10px rgba(249,115,22,0.1)",
  },
  workspace: {
    padding: "32px",
    borderRadius: "16px",
    minHeight: "650px",
  },
  tabContent: {
    display: "flex",
    flexDirection: "column",
    gap: "24px",
  },
  splitLayout: {
    display: "flex",
    gap: "24px",
    flexWrap: "wrap",
  },
  formPanel: {
    padding: "24px",
    borderRadius: "12px",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    flex: 1,
    background: "rgba(255,255,255,0.01)",
    border: "1px solid rgba(255,255,255,0.04)",
  },
  tableWrapper: {
    overflowX: "auto",
    background: "rgba(255,255,255,0.01)",
    border: "1px solid var(--card-border)",
    borderRadius: "12px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    textAlign: "left",
    fontSize: "14px",
  },
  loading: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "100vh",
    color: "var(--primary)",
    fontWeight: "700",
    fontSize: "18px",
  },
  row: {
    display: "flex",
    gap: "16px",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "inherit",
    fontSize: "14px",
    transition: "border-color 0.2s",
  },
  btnSmall: {
    padding: "6px 12px",
    fontSize: "12px",
    borderRadius: "6px",
    border: "none",
    cursor: "pointer",
    fontWeight: "600",
  },
  formCard: {
    padding: "16px",
    background: "rgba(255,255,255,0.02)",
    border: "1px solid rgba(255,255,255,0.05)",
    borderRadius: "8px",
  },
  adminProfileHero: {
    minWidth: "280px",
    flex: "0 0 300px",
    padding: "28px",
    borderRadius: "16px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "16px",
    textAlign: "center",
  },
  adminProfileAvatar: {
    width: "108px",
    height: "108px",
    display: "grid",
    placeItems: "center",
    overflow: "hidden",
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.14)",
    background: "linear-gradient(135deg, rgba(249, 115, 22, 0.28), rgba(59, 130, 246, 0.22))",
  },
  adminProfileAvatarImage: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover",
  },
  adminProfileAvatarFallback: {
    fontSize: "30px",
    fontWeight: "800",
    color: "#f8fafc",
    letterSpacing: "0.08em",
  },
  infoList: {
    display: "grid",
    gap: "12px",
  },
};
